//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTour
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tour
    {
        public int Tour_Id { get; set; }
        public Nullable<int> Route_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> Tour_Cost { get; set; }
        public Nullable<int> Tour_Duration { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Date_of_Depature { get; set; }
        public string Tour_Name { get; set; }
        public string Tour_Image_Name { get; set; }
    
        public virtual City City { get; set; }
        public virtual Route Route { get; set; }

        public string Email { get; set; }
        public string Name { get; set; }

        public string Number { get; set; }
    }
}
