//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTour
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bus_TourEntities1 : DbContext
    {
        public Bus_TourEntities1()
            : base("name=Bus_TourEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Place_in_the_route> Place_in_the_route { get; set; }
        public virtual DbSet<Place_Type> Place_Type { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<Route_Type> Route_Type { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<Country> Country { get; set; }
    }
}
